#!/usr/bin/env python3
"""
Auto-generate _sass/projects/_all.scss with imports for all project SASS files.
Scans _sass/projects/**/main.scss and creates import statements.
"""

import os
from pathlib import Path

# Paths
SASS_PROJECTS_DIR = Path("_sass/projects")
OUTPUT_FILE = SASS_PROJECTS_DIR / "_all.scss"

def generate_sass_imports():
    """Generate the _all.scss file with dynamic imports."""
    
    # Header
    header = """// AUTO-GENERATED PROJECT SASS IMPORTS
// This file is automatically generated during 'make dev' or 'make build'
// DO NOT EDIT MANUALLY - it will be overwritten
//
// To add a project's styles:
// 1. Create sass/main.scss in your project directory
// 2. Build will automatically detect and import it here

// Dynamic imports will be inserted below this line
// =================================================

"""
    
    # Find all project main.scss files
    imports = []
    if SASS_PROJECTS_DIR.exists():
        for project_dir in sorted(SASS_PROJECTS_DIR.iterdir()):
            if project_dir.is_dir() and project_dir.name != "__pycache__":
                main_scss = project_dir / "main.scss"
                if main_scss.exists():
                    # Generate relative import path
                    rel_path = f"{project_dir.name}/main"
                    imports.append(f'@import "{rel_path}";')
    
    # Write output
    content = header + "\n".join(imports) + "\n"
    
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(content)
    
    print(f"✅ Generated {len(imports)} SASS imports in {OUTPUT_FILE}")
    for imp in imports:
        print(f"   {imp}")

if __name__ == "__main__":
    generate_sass_imports()
